- name: "PLAY_1"
  hosts: local
  connection: local
  tasks:
  - name: "Task1"
    ansible.builtin.debug:
      msg: "Hello From PLAY_1 and Task1"
- name: "PLAY_2"
  hosts: local
  connection: local
  tasks: 
  - name: "task_2"
    ansible.builtin.debug:
      msg: "Hello from PLAY_2 and Task1"
      
    


