[web]
; 172.31.19.17 ansible_user=ec2-user ansible_password=DevOps321 COURSE="Devops" TOPIC="Ansible" LASTDAY="Sunday" #VARS_PREF="Var at inventory level"
localhost ansible_user=ec2-user ansible_password=DevOps321 #VARS_PREF="Var at inventory level"

[local]
localhost NAME="Vijay" TOPIC="Ansible" NEXT_TOPIC="TERRAFORM"